"""empty message

Revision ID: 911b229bae7a
Revises: d5bba62919dc
Create Date: 2021-01-08 12:14:39.672937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911b229bae7a'
down_revision = 'd5bba62919dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_image', sa.String(length=100), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_image')
    # ### end Alembic commands ###
